/***************************************************
	mined keyboard mapping table
	* generated with mkkbmap
	  from lib/kbmaps/yudit/Cyrillic.kmap
*/
struct keymap keymap_Cyrillic [] = {
	{"<<", "«"},	/* « = LEFT-POINTING DOUBLE ANGLE QUOTATION MARK = <Q> */
	{">>", "»"},	/* » = RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK = </Q> */
	{",,", "„"},	/* „ = DOUBLE LOW-9 QUOTATION MARK = <Q> */
	{"``", "“"},	/* “ = LEFT DOUBLE QUOTATION MARK = </Q> */
	{"N.", "№"},	/* № = NUMERO SIGN */
	{"C)", "©"},	/* © = COPYRIGHT SIGN */
	{"x)", "•"},	/* • = BULLET */
	{":)", "☺"},	/* ☺ = WHITE SMILING FACE */
	{":(", "☹"},	/* ☹ = WHITE FROWNING FACE */
	{"C-", "¤"},	/* ¤ = CURRENCY SIGN */
	{"E-", "€"},	/* € = EURO SIGN */
	{"L-", "£"},	/* £ = POUND SIGN */
	{"A", "А"},	/* А = CYRILLIC CAPITAL LETTER A  */
	{"B", "Б"},	/* Б = CYRILLIC CAPITAL LETTER BE */
	{"V", "В"},	/* В = CYRILLIC CAPITAL LETTER VE */
	{"G", "Г"},	/* Г = CYRILLIC CAPITAL LETTER GHE */
	{"D", "Д"},	/* Д = CYRILLIC CAPITAL LETTER DE */
	{"D-", "Ђ"},	/* Ђ = CYRILLIC CAPITAL LETTER DJE */
	{"G'", "Ѓ"},	/* Ѓ = CYRILLIC CAPITAL LETTER GJE */
	{"E", "Е"},	/* Е = CYRILLIC CAPITAL LETTER IE */
	{"E:", "Ё"},	/* Ё = CYRILLIC CAPITAL LETTER IO  */
	{"E>", "Є"},	/* Є = CYRILLIC CAPITAL LETTER UKRAINIAN IE */
	{"Z<", "Ж"},	/* Ж = CYRILLIC CAPITAL LETTER ZHE */
	{"Z", "З"},	/* З = CYRILLIC CAPITAL LETTER ZE */
	{"Z>", "Ѕ"},	/* Ѕ = CYRILLIC CAPITAL LETTER DZE */
	{"I", "И"},	/* И = CYRILLIC CAPITAL LETTER I */
	{"I`", "І"},	/* І = CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I */
	{"I:", "Ї"},	/* Ї = CYRILLIC CAPITAL LETTER YI */
	{"J<", "Ј"},	/* Ј = CYRILLIC CAPITAL LETTER JE */
	{"J", "Й"},	/* Й = CYRILLIC CAPITAL LETTER SHORT I */
	{"K", "К"},	/* К = CYRILLIC CAPITAL LETTER KA */
	{"L", "Л"},	/* Л = CYRILLIC CAPITAL LETTER EL */
	{"L>", "Љ"},	/* Љ = CYRILLIC CAPITAL LETTER LJE */
	{"M", "М"},	/* М = CYRILLIC CAPITAL LETTER EM */
	{"N", "Н"},	/* Н = CYRILLIC CAPITAL LETTER EN */
	{"N>", "Њ"},	/* Њ = CYRILLIC CAPITAL LETTER NJE */
	{"O", "О"},	/* О = CYRILLIC CAPITAL LETTER O */
	{"P", "П"},	/* П = CYRILLIC CAPITAL LETTER PE */
	{"R", "Р"},	/* Р = CYRILLIC CAPITAL LETTER ER */
	{"S", "С"},	/* С = CYRILLIC CAPITAL LETTER ES */
	{"T", "Т"},	/* Т = CYRILLIC CAPITAL LETTER TE */
	{"C'", "Ћ"},	/* Ћ = CYRILLIC CAPITAL LETTER TSHE */
	{"K'", "Ќ"},	/* Ќ = CYRILLIC CAPITAL LETTER KJE */
	{"U", "У"},	/* У = CYRILLIC CAPITAL LETTER U */
	{"U<", "Ў"},	/* Ў = CYRILLIC CAPITAL LETTER SHORT U */
	{"F", "Ф"},	/* Ф = CYRILLIC CAPITAL LETTER EF */
	{"H", "Х"},	/* Х = CYRILLIC CAPITAL LETTER HA */
	{"C", "Ц"},	/* Ц = CYRILLIC CAPITAL LETTER TSE */
	{"C<", "Ч"},	/* Ч = CYRILLIC CAPITAL LETTER CHE */
	{"D>", "Џ"},	/* Џ = CYRILLIC CAPITAL LETTER DZHE */
	{"S<", "Ш"},	/* Ш = CYRILLIC CAPITAL LETTER SHA */
	{"S>", "Щ"},	/* Щ = CYRILLIC CAPITAL LETTER SHCHA */
	{"\"\"", "Ъ"},	/* Ъ = CYRILLIC CAPITAL LETTER HARD SIGN */
	{"Y", "Ы"},	/* Ы = CYRILLIC CAPITAL LETTER YERU */
	{"\"", "Ь"},	/* Ь = CYRILLIC CAPITAL LETTER SOFT SIGN */
	{"E`", "Э"},	/* Э = CYRILLIC CAPITAL LETTER E */
	{"U>", "Ю"},	/* Ю = CYRILLIC CAPITAL LETTER YU */
	{"A>", "Я"},	/* Я = CYRILLIC CAPITAL LETTER YA */
	{"a", "а"},	/* а = CYRILLIC SMALL LETTER A */
	{"b", "б"},	/* б = CYRILLIC SMALL LETTER BE */
	{"v", "в"},	/* в = CYRILLIC SMALL LETTER VE */
	{"g", "г"},	/* г = CYRILLIC SMALL LETTER GHE */
	{"d", "д"},	/* д = CYRILLIC SMALL LETTER DE */
	{"d-", "ђ"},	/* ђ = CYRILLIC SMALL LETTER DJE */
	{"g'", "ѓ"},	/* г = CYRILLIC SMALL LETTER GJE */
	{"e", "е"},	/* е = CYRILLIC SMALL LETTER IE */
	{"e:", "ё"},	/* ё = CYRILLIC SMALL LETTER IO */
	{"e>", "є"},	/* є = CYRILLIC SMALL LETTER UKRAINIAN IE */
	{"z<", "ж"},	/* ж = CYRILLIC SMALL LETTER ZHE */
	{"z", "з"},	/* з = CYRILLIC SMALL LETTER ZE */
	{"z>", "ѕ"},	/* ѕ = CYRILLIC SMALL LETTER DZE */
	{"i", "и"},	/* и = CYRILLIC SMALL LETTER I */
	{"i`", "і"},	/* і = CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I */
	{"i:", "ї"},	/* ї = CYRILLIC SMALL LETTER YI */
	{"j<", "ј"},	/* ј = CYRILLIC SMALL LETTER JE */
	{"j", "й"},	/* й = CYRILLIC SMALL LETTER SHORT I */
	{"k", "к"},	/* к = CYRILLIC SMALL LETTER KA */
	{"l", "л"},	/* л = CYRILLIC SMALL LETTER EL */
	{"l>", "љ"},	/* љ = CYRILLIC SMALL LETTER LJE */
	{"m", "м"},	/* м = CYRILLIC SMALL LETTER EM */
	{"n", "н"},	/* н = CYRILLIC SMALL LETTER EN */
	{"n>", "њ"},	/* њ = CYRILLIC SMALL LETTER NJE */
	{"o", "о"},	/* о = CYRILLIC SMALL LETTER O */
	{"p", "п"},	/* п = CYRILLIC SMALL LETTER PE */
	{"r", "р"},	/* р = CYRILLIC SMALL LETTER ER */
	{"s", "с"},	/* с = CYRILLIC SMALL LETTER ES */
	{"t", "т"},	/* т = CYRILLIC SMALL LETTER TE */
	{"c'", "ћ"},	/* ћ = CYRILLIC SMALL LETTER TSHE */
	{"k'", "ќ"},	/* ќ = CYRILLIC SMALL LETTER KJE */
	{"u", "у"},	/* у = CYRILLIC SMALL LETTER U */
	{"u<", "ў"},	/* ў = CYRILLIC SMALL LETTER SHORT U */
	{"f", "ф"},	/* ф = CYRILLIC SMALL LETTER EF */
	{"h", "х"},	/* х = CYRILLIC SMALL LETTER HA */
	{"c", "ц"},	/* ц = CYRILLIC SMALL LETTER TSE */
	{"c<", "ч"},	/* ч = CYRILLIC SMALL LETTER CHE */
	{"d>", "џ"},	/* џ = CYRILLIC SMALL LETTER DZHE */
	{"s<", "ш"},	/* ш = CYRILLIC SMALL LETTER SHA */
	{"s>", "щ"},	/* щ = CYRILLIC SMALL LETTER SCHCHA */
	{"''", "ъ"},	/* ъ = CYRILLIC SMALL LETTER HARD SIGN */
	{"y", "ы"},	/* ы = CYRILLIC SMALL LETTER YERU */
	{"'", "ь"},	/* ь = CYRILLIC SMALL LETTER SOFT SIGN */
	{"e`", "э"},	/* э = CYRILLIC SMALL LETTER E */
	{"u>", "ю"},	/* ю = CYRILLIC SMALL LETTER YU */
	{"a>", "я"},	/* я = CYRILLIC SMALL LETTER YA */
	{"G`", "Ґ"},	/* Ґ = CYRILLIC CAPITAL LETTER GHE WITH UPTURN */
	{"g`", "ґ"},	/* ґ = CYRILLIC SMALL LETTER GHE WITH UPTURN */
	{"E<", "Ѣ"},	/* Ѣ = CYRILLIC CAPITAL LETTER YAT */
	{"e<", "ѣ"},	/* ѣ = CYRILLIC SMALL LETTER YAT */
	{"A<", "Ѫ"},	/* Ѫ = CYRILLIC CAPITAL LETTER BIG YUS */
	{"a<", "ѫ"},	/* ѫ = CYRILLIC SMALL LETTER BIG YUS */
	{"F`", "Ѳ"},	/* Ѳ = CYRILLIC CAPITAL LETTER FITA */
	{"f`", "ѳ"},	/* ѳ = CYRILLIC SMALL LETTER FITA */
	{"Y`", "Ѵ"},	/* Ѵ = CYRILLIC CAPITAL LETTER IZHITSA */
	{"y`", "ѵ"},	/* ѵ = CYRILLIC SMALL LETTER IZHITSA */
	{NIL_PTR}
};
