/***************************************************
	mined keyboard mapping table
	* generated with mkkbmap
	  from etc/kbmaps/yudit/Kazakh-prefix.kmap
	* with manual fix for grave prefix without extra space
*/
struct keymap keymap_Kazakh_prefix [] = {
	{"!", "!"},	/* ! = EXCLAMATION MARK */
	{"@", "\""},	/* " = QUOTATION MARK */
	{"#", "№"},	/* № = NUMERO SIGN */
	{"$", ";"},	/* ; = SEMICOLON */
	{"%", "%"},	/* % = PERCENT SIGN */
	{"^", ":"},	/* : = COLON */
	{"&", "?"},	/* ? = QUESTION MARK */
	{"*", "*"},	/* * = ASTERISK */
	{"(", "("},	/* ( = LEFT PARENTHESIS */
	{")", ")"},	/* ) = RIGHT PARENTHESIS */
	{"_", "_"},	/* _ = LOW LINE */
	{"+", "+"},	/* + = PLUS SIGN */
	{"Q", "Й"},	/* Й = CYRILLIC CAPITAL LETTER SHORT I */
	{"`Q", "Ұ"},	/* Ұ = CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE */
	{"W", "Ц"},	/* Ц = CYRILLIC CAPITAL LETTER TSE */
	{"E", "У"},	/* У = CYRILLIC CAPITAL LETTER U */
	{"`E", "Ү"},	/* Ү = CYRILLIC CAPITAL LETTER STRAIGHT U */
	{"R", "К"},	/* К = CYRILLIC CAPITAL LETTER KA */
	{"`R", "Қ"},	/* Қ = CYRILLIC CAPITAL LETTER KA WITH DESCENDER */
	{"T", "Е"},	/* Е = CYRILLIC CAPITAL LETTER IE */
	{"`T", "Ё"},	/* Ё = CYRILLIC CAPITAL LETTER IO */
	{"Y", "Н"},	/* Н = CYRILLIC CAPITAL LETTER EN */
	{"`Y", "Ң"},	/* Ң = CYRILLIC CAPITAL LETTER EN WITH DESCENDER */
	{"U", "Г"},	/* Г = CYRILLIC CAPITAL LETTER GHE */
	{"`U", "Ғ"},	/* Ғ = CYRILLIC CAPITAL LETTER GHE WITH STROKE */
	{"I", "Ш"},	/* Ш = CYRILLIC CAPITAL LETTER SH */
	{"O", "Щ"},	/* Щ = CYRILLIC CAPITAL LETTER SHCH */
	{"P", "З"},	/* З = CYRILLIC CAPITAL LETTER ZE */
	{"{", "Х"},	/* Х = CYRILLIC CAPITAL LETTER HA */
	{"`{", "Һ"},	/* Һ = CYRILLIC CAPITAL LETTER SHHA */
	{"A", "Ф"},	/* Ф = CYRILLIC CAPITAL LETTER EF */
	{"S", "Ы"},	/* Ы = CYRILLIC CAPITAL LETTER YERU */
	{"D", "В"},	/* В = CYRILLIC CAPITAL LETTER VE */
	{"F", "А"},	/* А = CYRILLIC CAPITAL LETTER A */
	{"`F", "Ә"},	/* Ә = CYRILLIC CAPITAL LETTER SCHWA */
	{"G", "П"},	/* П = CYRILLIC CAPITAL LETTER PE */
	{"H", "Р"},	/* Р = CYRILLIC CAPITAL LETTER ER */
	{"J", "О"},	/* О = CYRILLIC CAPITAL LETTER O */
	{"`J", "Ө"},	/* Ө = CYRILLIC CAPITAL LETTER BARRED O */
	{"K", "Л"},	/* Л = CYRILLIC CAPITAL LETTER EL */
	{"L", "Д"},	/* Д = CYRILLIC CAPITAL LETTER DE */
	{":", "Ж"},	/* Ж = CYRILLIC CAPITAL LETTER ZHE */
	{"\"", "Э"},	/* Э = CYRILLIC CAPITAL LETTER E */
	{"|", "/"},	/* / = SOLIDUS */
	{"Z", "Я"},	/* Я = CYRILLIC CAPITAL LETTER YA */
	{"X", "Ч"},	/* Ч = CYRILLIC CAPITAL LETTER CHE */
	{"C", "С"},	/* С = CYRILLIC CAPITAL LETTER ES */
	{"V", "М"},	/* М = CYRILLIC CAPITAL LETTER EM */
	{"B", "И"},	/* И = CYRILLIC CAPITAL LETTER I */
	{"`B", "І"},	/* І = CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I */
	{"N", "Т"},	/* Т = CYRILLIC CAPITAL LETTER TE */
	{"}", "Ъ"},	/* Ъ = CYRILLIC CAPITAL LETTER HARD SIGN */
	{"M", "Ь"},	/* Ь = CYRILLIC CAPITAL LETTER SOFT SIGN */
	{"<", "Б"},	/* Б = CYRILLIC CAPITAL LETTER BE */
	{">", "Ю"},	/* Ю = CYRILLIC CAPITAL LETTER YU */
	{"?", ","},	/* , = COMMA */
	{"1", "1"},	/* 1 = DIGIT ONE */
	{"2", "2"},	/* 2 = DIGIT TWO */
	{"3", "3"},	/* 3 = DIGIT THREE */
	{"4", "4"},	/* 4 = DIGIT FOUR */
	{"5", "5"},	/* 5 = DIGIT FIVE */
	{"6", "6"},	/* 6 = DIGIT SIX */
	{"7", "7"},	/* 7 = DIGIT SEVEN */
	{"8", "8"},	/* 8 = DIGIT EIGHT */
	{"9", "9"},	/* 9 = DIGIT NINE */
	{"0", "0"},	/* 0 = DIGIT ZERO */
	{"-", "-"},	/* - = HIPHEN-MINUS */
	{"0", "="},	/* = = EQUALS SIGN */
	{"q", "й"},	/* й = CYRILLIC SMALL LETTER SHORT I */
	{"`q", "ұ"},	/* ұ = CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE */
	{"w", "ц"},	/* ц = CYRILLIC SMALL LETTER TSE */
	{"e", "у"},	/* у = CYRILLIC SMALL LETTER U */
	{"`e", "ү"},	/* ү = CYRILLIC SMALL LETTER STRAIGHT U */
	{"r", "к"},	/* к = CYRILLIC SMALL LETTER KA */
	{"`r", "қ"},	/* қ = CYRILLIC SMALL LETTER KA WITH DESCENDER */
	{"t", "е"},	/* е = CYRILLIC SMALL LETTER IE */
	{"`t", "ё"},	/* ё = CYRILLIC SMALL LETTER IO */
	{"y", "н"},	/* н = CYRILLIC SMALL LETTER EN */
	{"`y", "ң"},	/* ң = CYRILLIC SMALL LETTER EN WITH DESCENDER */
	{"u", "г"},	/* г = CYRILLIC SMALL LETTER GHE */
	{"`u", "ғ"},	/* ғ = CYRILLIC SMALL LETTER GHE WITH STROKE */
	{"i", "ш"},	/* ш = CYRILLIC SMALL LETTER SH */
	{"o", "щ"},	/* щ = CYRILLIC SMALL LETTER SHCH */
	{"p", "з"},	/* з = CYRILLIC SMALL LETTER ZE */
	{"[", "х"},	/* х = CYRILLIC SMALL LETTER HA */
	{"`[", "һ"},	/* һ = CYRILLIC SMALL LETTER SHHA */
	{"a", "ф"},	/* ф = CYRILLIC SMALL LETTER EF */
	{"s", "ы"},	/* ы = CYRILLIC SMALL LETTER YERU */
	{"d", "в"},	/* в = CYRILLIC SMALL LETTER VE */
	{"f", "а"},	/* а = CYRILLIC SMALL LETTER A */
	{"`f", "ә"},	/* ә = CYRILLIC SMALL LETTER SCHWA */
	{"g", "п"},	/* п = CYRILLIC SMALL LETTER PE */
	{"h", "р"},	/* р = CYRILLIC SMALL LETTER ER */
	{"j", "о"},	/* о = CYRILLIC SMALL LETTER O */
	{"`j", "ө"},	/* ө = CYRILLIC SMALL LETTER BARRED O */
	{"k", "л"},	/* л = CYRILLIC SMALL LETTER EL */
	{"l", "д"},	/* д = CYRILLIC SMALL LETTER DE */
	{";", "ж"},	/* ж = CYRILLIC SMALL LETTER ZHE */
	{"'", "э"},	/* э = CYRILLIC SMALL LETTER E */
	{"\\", "\\"},	/* \ = REVERSE SOLIDUS */
	{"z", "я"},	/* я = CYRILLIC SMALL LETTER YA */
	{"x", "ч"},	/* ч = CYRILLIC SMALL LETTER CHE */
	{"c", "с"},	/* с = CYRILLIC SMALL LETTER ES */
	{"v", "м"},	/* м = CYRILLIC SMALL LETTER EM */
	{"b", "и"},	/* и = CYRILLIC SMALL LETTER I */
	{"`b", "і"},	/* і = CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I */
	{"n", "т"},	/* т = CYRILLIC SMALL LETTER TE */
	{"]", "ъ"},	/* ъ = CYRILLIC SMALL LETTER HARD SIGN */
	{"m", "ь"},	/* ь = CYRILLIC SMALL LETTER SOFT SIGN */
	{",", "б"},	/* б = CYRILLIC SMALL LETTER BE */
	{".", "ю"},	/* ю = CYRILLIC SMALL LETTER YU */
	{"/", "."},	/* . = FULL STOP */
	{NIL_PTR}
};
