#! /bin/sh

min=${1-1}
max=${2-${1-214}}

LC_ALL=C
export LC_ALL

rsdir=unihan.rs

echo "struct keymap keymap_Radical_Stroke [] = {"

r=$min
while [ $r -le $max ]
do
	echo ideographs with radical $r >& 2

#0	01 19968 一 U+4E00	
#1	01 19969 丁 U+4E01	
#1	01 19970 丂 U+4E02	
#... ->
#	{"1", "一 丁 丂 七 丄 丅"},

	sed -e "s,\(.*\)	[^ ]* [^ ]* \([^ ]*\) [^ ]*	*,\2 ," $rsdir/$r |
	tr -d '\012' |
	sed -e "s/^/	{\"$r\", \"/" -e 's/ *$/"},\
/'

	r=`expr $r + 1`
done

echo "	{NIL_PTR}"
echo "};"
