#! /bin/sh

# list files containing tables for all configured keyboard mappings

filter="grep -v Radical_Stroke"
filter=cat

# extract configured keyboard mappings from keymaps.cfg
confkeymaps=`LC_ALL=C sed -e '/^[-#]/ d' -e 's/^[ 	"]*\([^	]*\)		*\([A-Za-z0-9_][^ 	]*\).*\([^ 	][^ 	]\).*/\2.h/' -e t -e d keymaps.cfg |
	$filter
	`

kmlist=
for map in ${*:-$confkeymaps}
do	if [ -f "keymaps1/$map" ]
	then	km="keymaps1/$map"
	else	km="keymaps0/$map"
	fi
	kmlist="$kmlist $km"
	echo including "$km" >&2
done
echo $kmlist
