	{"de", "„“ ‚‘", "»« ›‹"}	/* German */,
	{"cs", "„“ ‚‘", "»« ›‹"}	/* Czech */,
	{"czech", "„“ ‚‘", "»« ›‹"}	/* Czech */,
	{"sk", "„“ ‚‘", "»« ›‹"}	/* Slovak */,
	{"slovak", "„“ ‚‘", "»« ›‹"}	/* Slovak */,
	{"sl", "„“ ‚‘", "»« ›‹"}	/* Slovene */,
	{"slovene", "„“ ‚‘", "»« ›‹"}	/* Slovene */,
	{"slovenian", "„“ ‚‘", "»« ›‹"}	/* Slovene */,
	{"is", "„“ ‚‘", NIL_PTR}	/* Icelandic */,
	{"hsb", "„“ ‚‘", NIL_PTR}	/* Sorbian */,
	{"dsb", "„“ ‚‘", NIL_PTR}	/* Sorbian */,
	{"ca", "«» “”", "“” ‘’"}	/* Catalan */,
	{"es", "«» “”", "“” ‘’"}	/* Spanish */,
	{"pt_BR", "“” ‘’", NIL_PTR}	/* Portuguese, Brazil */,
	{"pt", "«» ‹›", "“” ‘’"}	/* Portuguese */,
	{"az", "«» ‹›", "“” ‘’"}	/* Azerbaijani */,
	{"eu", "«» ‹›", "“” ‘’"}	/* Basque */,
	{"be", "«» „“", "„“"}	/* Belarusian */,
	{"uk", "«» „“", "„“"}	/* Ukrainian */,
	{"it", "«»", "“” ‘’"}	/* Italian */,
	{"fr_CH", "«» ‹›", NIL_PTR}	/* French, Swiss */,
	{"de_CH", "«» ‹›", NIL_PTR}	/* German, Swiss */,
	{"de_LI", "«» ‹›", NIL_PTR}	/* German, Liecht. */,
	{"it_CH", "«» ‹›", NIL_PTR}	/* Italian, Swiss */,
	{"br", "«» ‹›", NIL_PTR}	/* Breton */,
	{"gl", "«» ‹›", NIL_PTR}	/* Galician */,
	{"km", "«» ‹›", NIL_PTR}	/* Khmer */,
	{"fa", "«» ‹›", NIL_PTR}	/* Farsi */,
	{"hy", "«» “”", NIL_PTR}	/* Armenian */,
	{"sq", "«» ‹›", "“„ ‘‚"}	/* Albanian */,
	{"el", "«» ‟”", "“„ ‘‚"}	/* Greek */,
	{"greek", "«» ‟”", "“„ ‘‚"}	/* Greek */,
	{"fi", "”” ’’", "»» ››"}	/* Finnish */,
	{"sv", "”” ’’", "»»"}	/* Swedish */,
	{"ar_DZ", "«»", "”“"}	/* Arabic, Algeria */,
	{"ar_LB", "«»", "”“"}	/* Arabic, Lebanon */,
	{"ar_MA", "«»", "”“"}	/* Arabic, Morocco */,
	{"ar_SY", "«»", "”“"}	/* Arabic, Syria */,
	{"ar_TN", "«»", "”“"}	/* Arabic, Tunisia */,
	{"ar_DJ", "«»", "”“"}	/* Arabic, Djibouti */,
	{"ar_EH", "«»", "”“"}	/* Arabic, Western Sahara */,
	{"ar_KM", "«»", "”“"}	/* Arabic, Comoros */,
	{"ar_MR", "«»", "”“"}	/* Arabic, Mauritania */,
	{"ar_TD", "«»", "”“"}	/* Arabic, Chad */,
	{"ar", "”“", "«»"}	/* Arabic */,
	{"af", "“” ‘’", "„” ‚’"}	/* Afrikaans */,
	{"nl", "“” ‘’", "„” ‚’"}	/* Dutch */,
	{"bg", "„“", "«» ‘’"}	/* Bulgarian */,
	{"zh_HK", "『』 「」", "“” ‘’"}	/* Chinese, traditional */,
	{"zh_TW", "『』 「」", "“” ‘’"}	/* Chinese, traditional */,
	{"tchinese", "『』 「」", "“” ‘’"}	/* Chinese, traditional */,
	{"zh", "“” ‘’", NIL_PTR}	/* Chinese, simplified */,
	{"zh_CN", "“” ‘’", NIL_PTR}	/* Chinese, simplified */,
	{"chinese", "“” ‘’", NIL_PTR}	/* Chinese, simplified */,
	{"hr", "„” ‚’", "»«"}	/* Croatian */,
	{"hrvatski", "„” ‚’", "»«"}	/* Croatian */,
	{"croatian", "„” ‚’", "»«"}	/* Croatian */,
	{"da", "»« ›‹", "„“ ’’"}	/* Danish */,
	{"et", "„”", "„“"}	/* Estonian */,
	{"ko_KP", "《》 〈〉", NIL_PTR}	/* North Korean */,
	{"fr", "« » “ ”", "« » ‹ ›"}	/* French */,
	{"ka", "„“", "“”"}	/* Georgian */,
	{"he", "„” ‚’", "„“"}	/* Hebrew */,
	{"hebrew", "„” ‚’", "„“"}	/* Hebrew */,
	{"he_IL", "””", "”“"}	/* Hebrew, modern */,
	{"hu", "„” »«", "„” ’’"}	/* Hungarian */,
	{"hungarian", "„” »«", "„” ’’"}	/* Hungarian */,
	{"ja", "『』 「」", "【】 〖〗"}	/* Japanese */,
	{"japanese", "『』 「」", "【】 〖〗"}	/* Japanese */,
	{"ko", "“” ‘’", "『』 「」"}	/* Korean */,
	{"korean", "“” ‘’", "『』 「」"}	/* Korean */,
	{"lv", "«» „“", NIL_PTR}	/* Latvian */,
	{"lt", "„“", NIL_PTR}	/* Lithuanian */,
	{"lithuanian", "„“", NIL_PTR}	/* Lithuanian */,
	{"mk", "„“ ’‘", NIL_PTR}	/* Macedonian */,
	{"no", "«» ‘’", "”” ’’"}	/* Norwegian */,
	{"pl", "„” ‚’", "«» ‚’"}	/* Polish */,
	{"polish", "„” «»", "„” »«"}	/* Polish, altern. */,
	{"ro", "„” «»", NIL_PTR}	/* Romanian */,
	{"romanian", "„” «»", NIL_PTR}	/* Romanian */,
	{"ru", "«» „“", "“”"}	/* Russian */,
	{"russian", "«» „“", "“”"}	/* Russian */,
	{"kk", "«» „“", "“”"}	/* Kazakh */,
	{"tg", "«» „“", "“”"}	/* Tajik */,
	{"tt", "«» „“", "“”"}	/* Tatar */,
	{"sr_BA@latin", "„“ ’’", "„”"}	/* Serbian, Latin */,
	{"sr_CS@latin", "„“ ’’", "„”"}	/* Serbian, Latin */,
	{"sr_ME@latin", "„“ ’’", "„”"}	/* Serbian, Latin */,
	{"sr_RS@latin", "„“ ’’", "„”"}	/* Serbian, Latin */,
	{"sr", "„“ ‚’", "„”"}	/* Serbian, Cyrillic */,
	{"tr", "“” ‘’", "«» ‹›"}	/* Turkish */,
	{"turkish", "“” ‘’", "«» ‹›"}	/* Turkish */,
	{"vi", "«» ‹›", "“”"}	/* Vietnamese */,
